name: myarsips
description: "A new Flutter project to read PDF files."

publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  salomon_bottom_bar: ^3.3.2
  http: ^0.13.5
  http_client: ^1.5.2
  shared_preferences: ^2.3.3
  box: ^0.3.4
  js: ^0.7.1
  url_launcher: ^6.3.1
  flutter_pdfview: ^1.3.4
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: false  # Disabled material design

  # Add custom assets and fonts here if needed
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
